DROP USER IF EXISTS oberon_select;
CREATE USER 'oberon_select'@'%' IDENTIFIED BY 'Urubu100$';
GRANT ALL PRIVILEGES ON db.* TO 'oberon_select'@'%';
FLUSH PRIVILEGES;

DROP USER IF EXISTS oberon_crud;
CREATE USER 'oberon_crud'@'%' IDENTIFIED BY 'Urubu100$';
GRANT ALL PRIVILEGES ON db.* TO 'oberon_crud'@'%';
FLUSH PRIVILEGES;

DROP USER IF EXISTS dev;
CREATE USER 'dev'@'%' IDENTIFIED BY 'Urubu100$';
GRANT SELECT ON db.* TO 'dev'@'%';

FLUSH PRIVILEGES;
